language: python

python:
  - "3.5"

env:
  global:
    - ALLOWED_HOSTS: '127.0.0.1, .localhost'
    - SECRET_KEY: $SECRET_KEY

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: "python manage.py test"
