language: python

python:
  - "3.5"

env:
  global:
    - ALLOWED_HOSTS: '127.0.0.1, .localhost'
    - SECRET_KEY: 'r0u5dn8*79ro61^7mnk$m&qjcbdfv$9l*_(87rfbrl1b3#5^5h'

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: "python manage.py test"
